version: 0.0
os: linux
files:
 - source: /todolist/
   destination: /home/ec2-user/todolist
 - source: /manage.py
   destination: /home/ec2-user
 - source: /requirements.txt
   destination: /home/ec2-user

permissions:
  - object: /home/ec2-user/manage.py
    owner: ec2-user
    mode: 644
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
